name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Unit Tests
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:latest
        env:
          POSTGRES_USER: user
          POSTGRES_PASSWORD: password
          POSTGRES_DB: microservices
        ports:
          - 5432:5432

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r User_Service/requirements.txt
          pip install -r Order_Service/requirements.txt
          pip install pytest

      - name: Run Tests
        run: |
          source venv/bin/activate
          pytest User_Service/test_user.py
          pytest Order_Service/test_order.py

  build:
    name: Build Docker Images
    runs-on: ubuntu-latest
    needs: test  # Run only if tests pass

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Images
        run: |
          docker-compose build

  deploy:
    name: Deploy with Docker Compose
    runs-on: ubuntu-latest
    needs: build  # Run only if build succeeds

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy Services
        run: |
          docker-compose up -d
